clc; clear; close all; warning off all;
Img = imread("resim5.jpg");
Gray = rgb2gray(Img);
bw = imbinarize(Gray, .99);
bw = imcomplement(bw);
bw = imfill(bw, "holes");
bw = bwareaopen(bw, 100);
str = strel("disk", 5);
bw = imerode(bw, str);
Img2 = imread('resim6.jpg');
R = Img(:, :, 1);
G = Img(:, :, 2);
B = Img(:, :, 3);
R2 = Img2(:, :, 1);
G2 = Img2(:, :, 2);
B2 = Img2(:, :, 3);
bw_resized = imresize(bw, size(R2));
R_resized = imresize(R, size(R2));
G_resized = imresize(G, size(R2));
B_resized = imresize(B, size(R2));
R2(bw_resized) = R_resized(bw_resized);
G2(bw_resized) = G_resized(bw_resized);
B2(bw_resized) = B_resized(bw_resized);
RGB = cat(3, R2, G2, B2);
figure, imshow(RGB);